### ISSUE TITLE
A humble request.

### ISSUE THREAD

**Issue by GranakPavel** [afriscic/BarcodeScanning.Native.Maui#1]
Hello, would it be possible to modify the project to compile for the windows platform? It would be enough if Windows showed a blank page. Our application targets Android and Windows platforms (10.0.19041.0). The Android implementation is perfect, a colleague is developing for Windows and we are now unable to continue the project. I spent time editing your source code, but unfortunately I'm not at a good enough level to handle it now, I have to get my application live and I don't have time to spare now.
You have our great admiration.

**Comment by afriscic** [comment]
Unfortunately due to recent health issues i won't be able to do much work on this project. When everything gets resolved I'll update dependencies to ne west Version and try to do a Windows and MacOS implementation.
