### ISSUE TITLE
Restrict barcode detection to CameraView

### ISSUE THREAD

**Issue by SirJohnK** [afriscic/BarcodeScanning.Native.Maui#10]
Hi,

Let me start to say that I really like your library!!!

- My issue is that it seems like the image captured from the camera and used to detect barcodes do not match what is displayed in the CameraView. If you make a smaller CameraView, I still get detection from barcodes not visible in the view. 
- e.g. In the example below I get detection from both the barcode in view and the second barcode above, outside of view.
- I tried to analyze the code to see if I could help and make a PR, but I am unsure what to do.
- This is discovered on Android. (have not tested on iOS yet)
- Any Ideas?

/Regards Johan

![image](https://github.com/afriscic/BarcodeScanning.Native.Maui/assets/14839756/0dd828a6-b57c-414a-9a6f-ecbe016ea9cd)

**Comment by afriscic** [comment]
Yes, I haven’t implemented “viewfinder” capability yet. As my primary focus was fast scanning of multiple barcodes and the code to implement it looked too complicated to me at the time, I abandoned that feature.
Resolution of the video stream that goes to the analyser is decoupled from the preview size. Analyzer always gets a full video frame and preview is cropped depending on its size.

I understand that it is probably an essential feature for people that need precise scanning when multiple barcodes are in FOV. I’ll try to implement it, but it certainly won’t be before holidays, as this time of the year gets quite busy in my day job.

As a workaround you could implement some sort of “filtering” of detected barcodes by looking at their BoundingBox property as it is normalized to preview coordinates. So, if a detected barcode has a BoundingBox that is outside of preview you can ignore it.

**Comment by SirJohnK** [comment]
Thanks! Yes, I tried filtering based on BoundingBox. How do I get the "Bounding Box" for the preview to compare with? It seems like "display scale" come into play here!? e.g. when rectangles are drawn on the drawable canvas, the detected BoundingBox:es are scaled based on the "canvas.DisplayScale".  Negative coordinates are obviously outside preview, but how can I determine if positive coordinates are inside the preview?

**Comment by SirJohnK** [comment]
Hi again! :smiley:
I played around a bit with the code and came up with this.
- Added BarcodeFilter enum. 
- Added BarcodeFilter property to CameraView
- If BarcodeFilter is set to `InsidePreview`, all barcode outside preview will be filtered out in `BarcodeAnalyzer`.
```csharp
public enum BarcodeFilter
{
    None = 0,
    InsidePreview = 1,
}
```
In `CameraView`:
```csharp
public static readonly BindableProperty BarcodeFilterProperty = BindableProperty.Create(nameof(BarcodeFilter)
    , typeof(BarcodeFilter)
    , typeof(CameraView)
    , BarcodeFilter.None
    , defaultBindingMode: BindingMode.TwoWay
    , propertyChanged: (bindable, value, newValue) => ((CameraView)bindable).BarcodeFilter = (BarcodeFilter)newValue);

/// <summary>
/// Set the barcode filter.
/// Default value None.
/// </summary>
public BarcodeFilter BarcodeFilter
{
    get => (BarcodeFilter)GetValue(BarcodeFilterProperty);
    set => SetValue(BarcodeFilterProperty, value);
}
```
In `BarcodeAnalyzer`:
```csharp
if (_barcodeResults is not null && _cameraView is not null)
{
    if (_barcodeResults.Count > 0 && _cameraView.BarcodeFilter == BarcodeFilter.InsidePreview)
    {
        var previewRect = new RectF(_previewView.Left, _previewView.Top, _previewView.Width, _previewView.Height);
        _barcodeResults = _barcodeResults.Where(barcode => previewRect.Contains(barcode.BoundingBox)).ToHashSet();
    }

    _cameraView.DetectionFinished(_barcodeResults);
}
```
Finally set ´BarcodeFilter` in XAML:
```csharp
<barcode:CameraView
    x:Name="Barcode"
    BarcodeFilter="InsidePreview"
    BarcodeSymbologies="All"
    CameraEnabled="false"
    CaptureQuality="High"
    ForceInverted="False"
    HorizontalOptions="FillAndExpand"
    OnDetectionFinished="CameraView_OnDetectionFinished"
    TapToFocusEnabled="True"
    VerticalOptions="FillAndExpand"
    VibrationOnDetected="False" />
```

I am happy to make a PR on this, if you like it!

What do you think!?

**Comment by afriscic** [comment]
Thank you for ideas. I'll try to implement it ass soon as i have time.

**Comment by SirJohnK** [comment]
Ok. I will make a fork with my changes for you to see. If you like, when you have time, we can have further discussions and  I can make adjustments and make a PR. :smiley:

**Comment by afriscic** [comment]
I have found some free time this weekend and implemented two new features – Viewfinder mode and Aim mode. Viewfinder mode implements the features you requested. Feel free to test version 1.2.0 and report back any bugs. Especially on iOS as I have limited access to iOS device and unfortunately iOS simulator is useless for this library :(

**Comment by SirJohnK** [comment]
Great! 👍 I will test it out and return with results. 😃

**Comment by Quaybe** [comment]
The AimMode is wonderful! Tested on Android 13 and iOS 17 with iPhone 15 Pro. It works fantastic. Thank you!

It also seems to be working for inverted 1D barcodes on iOS, or am I mistaken??

**Comment by afriscic** [comment]
Yes, on Apple's Vision framework is much faster, better at detection, and AFAIK supports inverted codes (I have only tested 2D codes).
