### ISSUE TITLE
Support for net8.x

### ISSUE THREAD

**Issue by SimonBrettschneider** [afriscic/BarcodeScanning.Native.Maui#11]
First of all, thank you for a very nice plugin - the best QR scanner I have tried on Maui.

Would it possible to add "support" for .net8.0? It would be very handy when you have unit-test projects referencing your Maui project?

**Comment by afriscic** [comment]
I think it is doable. What do you think, would it be better to implement empty methods or to throw NotImplementedException on each method in handler (like in [https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.MediaElement/Handlers/MediaElementHandler.net.cs](url))?

**Comment by SimonBrettschneider** [comment]
I vote for NotImplementedException - if one would like to test the actual implementation it should be done per platform (android | iOS).

**Comment by afriscic** [comment]
Added in 1.2.1

**Comment by SimonBrettschneider** [comment]
Thank you for the update, but it is still not possible for a test project to reference my Maui project. All Barcode-specific types, such as OnDetectionFinishedEventArg or BarcodeResult, are marked as net8.0-android and net8.0-ios only.

Should I open a new issue, or can this be reopened?

**Comment by afriscic** [comment]
I'll reopen it but, unfortunately, I can't reproduce the problem. On my computer every type in Shared folder is correctly marked with all 3 targets and even when I made a new console app and referenced the Nuget package I was able to access all public types and methods.

**Comment by SimonBrettschneider** [comment]
My bad, this one is on me. After reinstalling the package, everything works as expected. Please close this issue.
