### ISSUE TITLE
Lag in camera scanner 

### ISSUE THREAD

**Issue by elqubed84** [afriscic/BarcodeScanning.Native.Maui#115]
The library is great but during the barcode scanning test the camera slows down like lag in the camera
The same goes for searching for two codes together
qrcode + ean13
A year late in reading
Is there a solution?
The project is net maui version 9

**Comment by elqubed84** [comment]
![Recorder_20112024_161931](https://github.com/user-attachments/assets/b39e8d3f-d354-44e5-aac6-07020059eeb7)
This is example

**Comment by afriscic** [comment]
Try to cone this repository and try running Barcodescanning.Test on your device to see how it works.
From my experience all supported iPhones run completely fluid. on Android it runs good even on low end devices with `ForceInverted` set fo `false`. If you set it to `true` it has a performance penalty which is higher on low end devices.

**Comment by elqubed84** [comment]
My Dear [afriscic](https://github.com/afriscic)
Thank you sir, the camera became very normal after taking your advice, but I want to decode QR codes and ean-13 codes only
Because the reading is still very weak, and I think that if I can determine the types of codes, it may help the library to read
Second question
Is it possible to take a picture of the QR code after reading?
