### ISSUE TITLE
any help

### ISSUE THREAD

**Issue by elqubed84** [afriscic/BarcodeScanning.Native.Maui#116]
The library is very valuable and fast to read. Please, gentlemen who were able to install it and it worked for them without problems, tell us the version they worked with, the work environment, the .NET version, and the Visual Studio version, because it is a very beautiful library and it would be a shame that we do not benefit from it.

**Comment by elqubed84** [comment]
I think the developer is the one who will answer these questions, as he is the one who conducted the experiment.

**Comment by niza93** [comment]
v1.6.0 works fine on MAUI 9.0.10 with Visual Studio 17.13.0 Preview 1.0

**Comment by elqubed84** [comment]
niza93  thanks
