### ISSUE TITLE
Update docs about `OnDetectionFinishedCommand`

### ISSUE THREAD

**Issue by riccardominato** [afriscic/BarcodeScanning.Native.Maui#117]
The main readme of the repo says:

> or bind OnDetectionFinishedCommand property to a Command in your ViewModel:
> ```xaml
> <scanner:CameraView ...
>                     OnDetectionFinishedCommand="{Binding DetectionFinishedCommand}"
>                     .../>
> ```
> ```csharp
> public ICommand DetectionFinishedCommand { get; set; }
> ...
> DetectionFinishedCommand = new Command<BarcodeResult[]>(BarcodeResult[] result) =>
> {
>     if (result.Length > 0)
>         ...
> }
> ```

With .NET9 this won't work anymore. Maybe it should be replaced by:
```csharp
DetectionFinishedCommand = new Command<IReadOnlySet<BarcodeResult>>(IReadOnlySet<BarcodeResult> result) =>
{
    if (result.Count > 0)
        ...
}
```

with a note specifying that for versions <2.0.0 `BarcodeResult[]` should be used instead.

If this is correct, I could make a PR!

**Comment by afriscic** [comment]
Thank you for info. Updated

**Comment by riccardominato** [comment]
@afriscic Please note that `BarcodeResult[]` is still there in readme.

```csharp
DetectionFinishedCommand = new Command<BarcodeResult[]>(IReadOnlySet<BarcodeResult> result) =>
{
    if (result.Count > 0)
        ...
}
```
