### ISSUE TITLE
Scanning with 3 lens iPhones isn't possible

### ISSUE THREAD

**Issue by Lucia-Bader** [afriscic/BarcodeScanning.Native.Maui#12]
Since the iOS CameraViewHandler always uses the BuiltInWideAngleCamera which doesn’t support close range focus for devices with 3 lenses and therefore scanning with 3 lens iPhones (e. g. iPhone 13 Pro & iPhone 15 Pro Max) isn’t possible. Based on [https://github.com/JimmyPun610/BarcodeScanner.Mobile/issues/202#issuecomment-1834844897](url) I was able to adapt the CameraViewHandler as follows so sthat scanning is also possible with iPhones with 3 lenses.

Inside UpdateCamera() I replaced following code:
```
_captureDevice = AVCaptureDevice.GetDefaultDevice(
    AVCaptureDeviceType.BuiltInWideAngleCamera,
    AVMediaTypes.Video,
    VirtualView?.CameraFacing == CameraFacing.Front ? AVCaptureDevicePosition.Front : AVCaptureDevicePosition.Back);
_captureDevice ??= AVCaptureDevice.GetDefaultDevice(AVMediaTypes.Video);
```

with following code:
```
var position = VirtualView.CameraFacing == CameraFacing.Front ? AVCaptureDevicePosition.Front : AVCaptureDevicePosition.Back;
_captureDevice = GetCaptureDevice(position);
```

and the implementation of GetCaptureDevice() looks as follows:
```
private static AVCaptureDevice GetCaptureDevice(AVCaptureDevicePosition position)
 {
     AVCaptureDevice captureDevice = AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInTripleCamera, AVMediaTypes.Video, position);
     captureDevice ??= AVCaptureDevice.GetDefaultDevice(AVCaptureDeviceType.BuiltInDualCamera, AVMediaTypes.Video, position);
     captureDevice ??= AVCaptureDevice.DevicesWithMediaType(AVMediaTypes.Video.GetConstant()).FirstOrDefault( d => d.Position == position);

     return captureDevice;
 }
```

Would it be bossible to add support for 3 lens iPhone scanning based on the CameraViewHandler modifications described in this issue?

**Comment by afriscic** [comment]
Thank you very much for great feedback. I'll implement this ASAP in next release

**Comment by Lucia-Bader** [comment]
Sounds good, thank you!

**Comment by afriscic** [comment]
Added in 1.2.1. Have a go at testing it and report back any bugs

**Comment by Quaybe** [comment]
It is working for my iPhone 15 Pro with 3 lenses. You're awesome, @afriscic !
