### ISSUE TITLE
qrcode image 

### ISSUE THREAD

**Issue by elqubed84** [afriscic/BarcodeScanning.Native.Maui#120]
Why when the QR code is detected, the image is taken by rotating it 90 degrees to the left?

This makes determining the location of the QR code inaccurate.

Is there a solution?

My idea is to crop the image and make the qrcode the only one in the image.

Is there a solution?
thanks

**Comment by elqubed84** [comment]
I tried to crop the image using BarcodeResult.ImageBoundingBox
But the cropped image was always in the wrong place and did not display the QR code image
Currently I found a solution which is to display the image on the zxing.net library and from there I get the ResultPoints and then I crop it
This solution displays the cropped image of the code correctly but this takes a lot of time and memory
As I have to convert the image to Bitmamap and after finishing cropping I convert it back to stream to display it
As I mentioned this is a difficult solution
Do you have a good idea
Knowing that the code
canvas.DrawRectangle(barcode.PreviewBoundingBox);
draws the square very well
Here is the code

`private async void CameraView_OnDetectionFinished(object sender, OnDetectionFinishedEventArg e)
{
    _drawable.barcodeResults = e.BarcodeResults.ToHashSet();
    if (e.BarcodeResults.Any())
    {
        if (!_isBarCodeDetected)
        {
            var barcodeResult = e.BarcodeResults.FirstOrDefault(result => result.BarcodeFormat != BarcodeFormats.QRCode);
            if (barcodeResult != null)
            {
                _isBarCodeDetected = true;
                barvalue = barcodeResult.RawValue;
                zxing.CaptureNextFrame = false;
                return;
            }
        }
        if (_isBarCodeDetected && !_isQrCodeDetected)
        {
            var qrCodeResult = e.BarcodeResults.FirstOrDefault(result => result.BarcodeFormat == BarcodeFormats.QRCode);
            if (qrCodeResult != null)
            {
                qrvalue = qrCodeResult.RawValue;
                _isQrCodeDetected = true;
                zxing.CaptureNextFrame = true;
                zxing.PauseScanning = true;
                await Task.Run(async () =>
                {
                    try
                    {
                        var eventArg = new OnImageCapturedEventArg { Image = _drawable.image };
                        if (eventArg?.Image != null)
                        {
                            await PlaySound("beeb2.mp3");
                            lOADER.Dispatcher.Dispatch(() => lOADER.IsVisible = true);
                            DeterminateProgressBar.Dispatcher.Dispatch(() =>
                                DeterminateProgressBar.Progress += 30);
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Error: {ex.Message}");
                    }
                });
            }
        }
        if (!_isBarCodeDetected && !_isQrCodeDetected)
        {
            zxing.PauseScanning = false;               
        }
    }
    squaree.Invalidate();
}

private async void CameraView_OnImageCaptured(object sender, OnImageCapturedEventArg e)
{
    if (e.Image == null)
        return;
    try
    {
        await Task.Run(async () =>
        {
            if (lang.StartsWith("ar"))
                await PlaySound("analysis.mp3");
            else
                await PlaySound("analysisen.mp3");
            using (var originalStream = e.Image.AsStream())
            {
                originalStream.Position = 0;
                using (var memoryStream = new MemoryStream())
                {
                    await originalStream.CopyToAsync(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();
                    var croppedBitmap = await DecodeQRCodeAndCropAsync(imageBytes);
                    if (croppedBitmap != null)
                    {
                        using (var croppedMemoryStream = new MemoryStream())
                        {
                            croppedBitmap.Encode(croppedMemoryStream, SKEncodedImageFormat.Jpeg, 50);
                            croppedMemoryStream.Position = 0;
                            byte[] croppedImageBytes = croppedMemoryStream.ToArray();
                            MainThread.BeginInvokeOnMainThread(async () =>
                            {
                                qrcode1.Source = ImageSource.FromStream(() => new MemoryStream(croppedImageBytes));
                                screen.IsVisible = true;
                                await SaveImageToFileAsync(croppedImageBytes);
                                DeterminateProgressBar.Progress += 30;
                                await SendData(qrvalue, barvalue, croppedImageBytes);
                            });
                        }
                    }
                    else
                    {
                        MainThread.BeginInvokeOnMainThread(async() =>
                        {
                            if (lang.StartsWith("ar"))
                                await PlaySound("noanalysis.mp3");
                            else
                                await PlaySound("noanalysisen.mp3");
                            zxing.PauseScanning = false;
                            lOADER.IsVisible = false;
                            qrvalue = null;
                            barvalue = null;
                            _isBarCodeDetected = false;
                            _isQrCodeDetected = false;
                            DeterminateProgressBar.Progress = 0;
                        });
                        return;
                    }
                }
            }
        });
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error: {ex.Message}");
    }
}

public async Task<SKBitmap> DecodeQRCodeAndCropAsync(byte [] imageStream)
{
    try
    {
        var bitmap = SKBitmap.Decode(imageStream);
        if (bitmap == null) return null;
        var reader = new ZXing.SkiaSharp.BarcodeReader
        {
            AutoRotate = true,
            Options = new ZXing.Common.DecodingOptions
            {
                PossibleFormats = new[] { BarcodeFormat.QR_CODE },
                TryHarder = true,
                TryInverted = false
            }
        };
        var result = reader.Decode(bitmap);
        if (result == null || result.ResultPoints.Length != 4) return null;
        int margin = 55; 
        int topPadding = 0; 
        int minX = Math.Max((int)result.ResultPoints.Min(p => p.X) - margin - topPadding, 0);
        int minY = Math.Max((int)result.ResultPoints.Min(p => p.Y) - margin , 0); // إضافة الهامش العلوي
        int maxX = Math.Min((int)result.ResultPoints.Max(p => p.X) + margin, bitmap.Width);
        int maxY = Math.Min((int)result.ResultPoints.Max(p => p.Y) + margin, bitmap.Height);
        var rect = new SKRect(minX, minY, maxX, maxY);
        var croppedBitmap = CropBitmap(imageStream, rect);
        var res = reader.Decode(croppedBitmap);
        if (res == null)
            return null;
        else
            return croppedBitmap;
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
        return null;
    }
}

private SKBitmap CropBitmap(byte[] imageBytes, SKRect rect, float rotationAngle = 90)
{
    SKBitmap source;
    using (var stream = new MemoryStream(imageBytes))
    using (var managedStream = new SKManagedStream(stream))
    {
        source = SKBitmap.Decode(managedStream);
        if (source == null)
        {
            throw new ArgumentException("Invalid image bytes or unsupported image format.");
        }
    }
    var croppedBitmap = new SKBitmap((int)rect.Width, (int)rect.Height);
    using (var canvas = new SKCanvas(croppedBitmap))
    {
        var dest = new SKRect(0, 0, rect.Width, rect.Height);
        canvas.DrawBitmap(source, rect, dest);
    }
    int newWidth = croppedBitmap.Height; // العرض الجديد يصبح الارتفاع الأصلي
    int newHeight = croppedBitmap.Width; // الارتفاع الجديد يصبح العرض الأصلي
    var rotatedBitmap = new SKBitmap(newWidth, newHeight);
    using (var canvas = new SKCanvas(rotatedBitmap))
    {
        canvas.Translate(newWidth / 2f, newHeight / 2f);
        canvas.RotateDegrees(rotationAngle);
        canvas.Translate(-croppedBitmap.Width / 2f, -croppedBitmap.Height / 2f);
        canvas.DrawBitmap(croppedBitmap, 0, 0);
    }
    return rotatedBitmap;
}`

**Comment by afriscic** [comment]
I can confirm that the rotation is skewed.
I'll fix this in next release
