### ISSUE TITLE
Question: Running App on Windows with This Package

### ISSUE THREAD

**Issue by Quaybe** [afriscic/BarcodeScanning.Native.Maui#14]
My app is going to be for iOS, Android, and Windows. It has many facets, not just the barcode scanner. How would I make it to where I can run the app in Windows with just this barcode feature disabled since it is not compatible?

**Comment by afriscic** [comment]
I'm not comfortable to add Windows as an "empty" target as I think it'll add more confusion. Windows support is planned but I don't think it will be in the near future.
You can fork this project and add Windows target as i did with .NET target in 1.2.1 or you can configure your project to add this package only on iOS and Android.

**Comment by Quaybe** [comment]
Thanks for the reply! I apologize as I'm a bit of a noob.

**Comment by Quaybe** [comment]
@afriscic I'm sorry to bug on this. Are there any resources you could point me to that will inform me how to do what you suggest?

I've done a lot of conditional includes to prevent the C# side of my code from including the Barcode scanning methods if I'm targeting Windows. However, I can't figure out how to do the same for my barcode scanner **view**. I can't figure out how to ignore the view if I'm targeting Windows, and I'm also not sure how to make the fork target Windows.

I don't need a step by step, but if you find the time to point me in the right direction to accomplish this, I'd be eternally grateful.

**Comment by Quaybe** [comment]
Nevermind, good sir... I think I finally got it going. I look forward to full Windows implementation one day!
