### ISSUE TITLE
Scan Distance and Polling Interval

### ISSUE THREAD

**Issue by hhuumm** [afriscic/BarcodeScanning.Native.Maui#16]
Hey Afriscic,

Happy new year! 

We were able to use your package for a demo application.  Wanted to ask about polling intervals and scan distance. 

How can we increase the effective scan distance from the barcodes? While the scanning works remarkably at stand still and relatively well in motion(my last issue), we  have to be really close to the barcodes to get a pickup. Wanted to ask you if there is a way to configure the effective distance, and if there is some parameter we could tweak(aside from resolution quality, we have that set to "Highest") so that it may read at further distances?

Also we often find that after a while the camera will stop scanning. In our particular use-case, we want to stop scanning after a number of scans rather than a time interval. The current workaround is a button to manually reset the camera, but I wanted to ask the chef himself if there is a configuration for the camera to work as a function of scans rather than time and how the polling interval plays a role in all this. Could we set it to always scan and manually turn off the scanning?

Looking forward to your response, and again great work on the package.

**Comment by afriscic** [comment]
Hello.

Distance could (maybe) be improved by using telephoto camera on devices with multiple cameras. On Iphone it is implemented with "triple" camera selection but on Android camera selection, besides default camera, is a bit of a pain. I'll consider implementing some kind if camera selection logic on Android but no ETA.
Or scanning distance could be improved with commercial barcode scanning solutions. In my experience they are better than these that come with Android and iOS for free.

As for barcode counting, you can ignore Pooling and implement your own counter that increments every time you detect a barcode in OnDetectionFinished event. Then just set PauseScanning property to true when you want to pause scanning. You can resume scanning by setting PauseScanning to false at any time.
