### ISSUE TITLE
Edge detection

### ISSUE THREAD

**Issue by vikern22** [afriscic/BarcodeScanning.Native.Maui#17]
Hi!

Struggling a bit understanding the docs here - but is it possible to do simple edge detection for capturing images of receipts or invoices with this library? Something like: [https://media.idownloadblog.com/wp-content/uploads/2015/10/Scanbot-4.3-for-iOS-Magic-filter-comparison.jpg](url)

**Comment by afriscic** [comment]
Hello.

No, this is not implemented in this project. This project is only for barcode detection and decoding. Supported barcode symbologies are in the readme.
