### ISSUE TITLE
Torch not turning on - iOS

### ISSUE THREAD

**Issue by SimonBrettschneider** [afriscic/BarcodeScanning.Native.Maui#19]
Hi

First of all, thank you for a nice plugin.

I tried using the torch function on Android and iOS

`TorchOn="True"`

It seems to work fine on Android but nothing happens on iOS. Can you confirm that it works on iOS?

**Comment by afriscic** [comment]
Hello.

Unfortunately I don't have an iOS device on hand to test it. I tested it and it worked a couple releases back but some bug can crawl in there... I'll try to test it ASAP.
What device do you use?

If anyone else can confirm this or share a fix it would be very helpful.

**Comment by afriscic** [comment]
Tested today with 1.2.4 release and torch worked OK on iOS

**Comment by SimonBrettschneider** [comment]
Hi

I have tested on 1.2.4 and setting `TorchOn` in code-behind works as expected on Android and iOS. This issue should be closed.
