### ISSUE TITLE
Not an issue - I Apologize

### ISSUE THREAD

**Issue by rsimmermon** [afriscic/BarcodeScanning.Native.Maui#22]
I'm sorry, this is not an issue, but I can't find another place to contact the developer.  One issue with the BarcodeScanner.Mobile.MAUI is that it seemed to have a dependency somewhere in the tree on bitcode.  So apple rejects it and I had to do a lengthy workaround to remove the bitcode.
Also, the Android Simulator on an arm64 architecture on my Mac doesn't appear to work with some Google Vision ML kit stuff.

Are both of these issue addresses/gone in your version?

Thank you!!

**Comment by afriscic** [comment]
Hello.

On iOS this project doesn't have any external dependencies. Everything that is referenced comes with MAUI out of the box.
I haven't done extensive testing in Android Simulator as it isn't practical for this use case, but i haven't seen any differences from physical devices other that in simulator everything was significantly slower...

**Comment by rsimmermon** [comment]
Thank you for the quick response.  I can confirm now that it does indeed fix the issue I was having running the android version on an arm64 Mac.  Just thought I'd share in case someone else wanted to know.
