### ISSUE TITLE
OnDetectionFinished Event Gets called immediately in ContentView

### ISSUE THREAD

**Issue by rsimmermon** [afriscic/BarcodeScanning.Native.Maui#23]
I have this in my xaml view

        
        <Frame Grid.Row="0" IsClippedToBounds="true" Padding="0" HorizontalOptions="Fill" VerticalOptions="Fill">
            <barcode:CameraView
                HorizontalOptions="Fill"
                VerticalOptions="Fill"
                x:Name="Barcode"
                CaptureQuality="High"
                ForceInverted="False"
                TapToFocusEnabled="True"
                BarcodeSymbologies="All"
                OnDetectionFinished="BarcodeDetected" />
            
        </Frame>

in the code behind, I put a breakpoint on my BarcodeDetected method, and it's called immediately when the content view is shown.
In fact, every time I continue, it gets called again immediately.

I am using the component in a ContentVIew that is getting swapped with another view via a shared, injected service.

Has anyone ran into the "OnDetectionFinished" getting called rapidly and immediately?
I got this to work as a workaround, but it's not ideal:

    private void BarcodeDetected(object sender, OnDetectionFinishedEventArg e)
    {
        if (e.BarcodeResults?.Any() ?? false)
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                BarcodeScannedEvent?.Invoke(e.BarcodeResults.FirstOrDefault());
            });
        }
    }

**Comment by afriscic** [comment]
This is by design. OnDetectionFinished is called every time BarcodeAnalyzer finishes processing, if everything works well multiple times a second. This is to enable continuous feedback of the scanning process and BarcodeResults should never return null.
You can do a simpler if statement to check if any results are present:private void BarcodeDetected(object sender, 
```
OnDetectionFinishedEventArg e)
{
    if (e.BarcodeResults.Count > 0)
    {
            foreach (var barcode in e.BarcodeResults)
            {
                //Do something with results...
            }
    }
    else
    {
            // Do something if no barcode is detected...
    }
}
```
