### ISSUE TITLE
'APK already contains the item libbarhopper' warnings

### ISSUE THREAD

**Issue by HavenDV** [afriscic/BarcodeScanning.Native.Maui#27]
After adding the library I get these warnings when building
```
0>libbarhopper_v3.so: Warning XA4301 : APK already contains the item lib/armeabi-v7a/libbarhopper_v3.so; ignoring.
0>libbarhopper_v3.so: Warning XA4301 : APK already contains the item lib/x86/libbarhopper_v3.so; ignoring.
0>libbarhopper_v3.so: Warning XA4301 : APK already contains the item lib/arm64-v8a/libbarhopper_v3.so; ignoring.
0>libbarhopper_v3.so: Warning XA4301 : APK already contains the item lib/x86_64/libbarhopper_v3.so; ignoring.
```
If there is a way to remove them other than `<NoWarn>$(NoWarn);XA4301</NoWarn>`?

**Comment by afriscic** [comment]
Sorry, Google tells me that it is probably because libbarhopper_v3.so is referenced in multiple packages so it gets copied multiple times which results in this warning. So i guess it is OK to ignore it...

**Comment by riccardominato** [comment]
Just adding my little bit to this. I had the same problem and I opened an issue to Xamarin repo.
They answer that yes, it's safe to ignore it.

If you want to go underneath the warning, this is the issue.
https://github.com/xamarin/GooglePlayServicesComponents/issues/819
