### ISSUE TITLE
Add ability to remove aiming dot when AimMode is on

### ISSUE THREAD

**Issue by kklose23** [afriscic/BarcodeScanning.Native.Maui#28]
I like what AimMode provides, but I wanted a way to not show the aiming dot.  I went to add to the `CameraViewMapper` of the `CameraViewHandler`, but `RemoveAimingDot` is marked as `internal`

**Comment by afriscic** [comment]
Hello.
I think that would only confuse the user. But you could easily implement it yourself. When OnDetectionFinished returns barcodes just reject any barcode whose BoundingBox doesn't contain a Point with coordinates matching your views center.
