### ISSUE TITLE
Android crashes when opening barcode scanner with R8 Code Shrinker enabled in Release mode

### ISSUE THREAD

**Issue by Quaybe** [afriscic/BarcodeScanning.Native.Maui#34]
As the title states, when attempting to open the barcode scanner, the app crashes. This is **only** with R8 code shrinker enabled in Release mode. It works if I remove the R8 code shrinker, and it works in iOS.

**Comment by afriscic** [comment]
Hello.
Unfortunately I'm not that familiar with debugging R8 code shrinker. If you could post some error log or dump maybe someone could figure something out.

**Comment by DerFachinformatiker** [comment]
I had the same problem and after a long research I got an easy fix for it.
R8 cleans your code of unneeded code to shrink it, but if you don't protect your code it cleans your code even from needed code sometimes. (Too much code in one sentence) Well long code short, normally there is a file with instructions for the cleaning to protect you code. But I don't know if it's Microsoft or some other who think this file is useless, and it's nowadays not created on installation. As long as I need to write the solution as short is the solution itself. 

You need to create a file at the exact same location.
C:\Program Files (x86)\Android\android-sdk\tools\proguard\proguard-android.txt

Fill this file with the following code.
https://android.googlesource.com/platform/sdk/+/refs/heads/main/files/proguard-android.txt

After I have done this, the app didn't crash anymore on the release build with r8 enabled.

**Comment by afriscic** [comment]
Thanks for sharing this solution!

**Comment by Quaybe** [comment]
I will give it a try, thank you. I apologize for the lack of information on my part.
