### ISSUE TITLE
Is .NET 7 supported?

### ISSUE THREAD

**Issue by thdigalakis** [afriscic/BarcodeScanning.Native.Maui#35]
Hello and thanks a lot for your library.
I want to ask if there is  a chance to use it with .NET 7?

Thanks in advance!

**Comment by afriscic** [comment]
Hello.
I think it could be done, but it would require more testing. No ETA for now.

**Comment by sbricchi** [comment]
I vote for this too! It would be great to make it work in NET 7. I've tried myself but I got stuck with some dependencies error. 
On the first place, there are some C# 12 minor features that needs to be taken back to C# 11. 
After that I have some java compiler error with "androidx.lifecycle.lifecycle-common" that is out of my reach...
Thanks in advance in case you ever have the time to try!
