### ISSUE TITLE
Usage in .net6.0-android (NOT Maui or Xamarin.Forms)

### ISSUE THREAD

**Issue by amirvenus** [afriscic/BarcodeScanning.Native.Maui#44]
Hi,

I was wondering if anyone's had any experience using this library without maui and when targetting .net6.0-android only (formerly known as Xamarin native)?

Thanks!

**Comment by afriscic** [comment]
Hello.
This library is for MAUI only but if you would like to use it for Xamarin android you should be able to reuse most i think you can reuse most of the code that is in [BarcodeView.cs](https://github.com/afriscic/BarcodeScanning.Native.Maui/blob/master/BarcodeScanning.Native.Maui/Platform/Android/BarcodeView.cs) as it is all Android specific.
