### ISSUE TITLE
Video is frozen when attempt to call page a second time

### ISSUE THREAD

**Issue by be-swarm** [afriscic/BarcodeScanning.Native.Maui#5]
Step to reproduce:
Create a page with your control.
register it in di
 builder.Services.AddSingleton<YourPage>();

Navigate to your page. All is ok.
Navigate back and navigate to your page a second time.
Video is frozen.

Workaround found:
Inject page with transient scope
 builder.Services.AddTransient<YourPage>();

**Comment by afriscic** [comment]
Try to add it in DI as transient and/or override OnDisappearing and set CameraEnabled to false to close the camre before you move out of the page, and then set CameraEnabled to true in OnAppearing override to enable the camera again.
