### ISSUE TITLE
OnDetectionFinishedEventArg ~ OnDetectedEventArg 

### ISSUE THREAD

**Issue by NorMoll** [afriscic/BarcodeScanning.Native.Maui#55]
OnDetectionFinishedEventArg is duplicated in OnDetectedEventArg class

**Comment by afriscic** [comment]
As of 1.5.0 there are two events that can get triggered:
`public event EventHandler<OnDetectionFinishedEventArg> OnDetectionFinished;`
`public event EventHandler<OnImageCapturedEventArg> OnImageCaptured;`
