### ISSUE TITLE
 OnDetectionFinishedCommand?.Execute(results); never executes

### ISSUE THREAD

**Issue by NorMoll** [afriscic/BarcodeScanning.Native.Maui#56]
Although the  TriggerOnDetectionFinished method is called the OnDetectionFinishedCommand?.Execute(results); never executes. It also seems that the TriggerOnDetectionFinished method is enetered for any camera activity and not only when barcodes are detected.

**Comment by afriscic** [comment]
`TriggerOnDetectionFinished` gets triggered every time camera frame is processed, regardless of whether a barcode is detected or not.
