### ISSUE TITLE
Scan box

### ISSUE THREAD

**Issue by garcia252** [afriscic/BarcodeScanning.Native.Maui#59]
This library is remarkably good in scanning barcodes and QR codes. However, is there any possibility to have a scan box or similar instead of the red dot aim? (such as https://user-images.githubusercontent.com/68213/58515686-9c98ea00-8173-11e9-9152-eeaac1e2a464.png)

**Comment by afriscic** [comment]
Hello.

To be honest, I'm quite reluctant to implement different scanning overlays as everybody likes something different and maintaining native UI for every platform is a bit of a hassle.
You can implement this inside MAUI itself if you put `GraphicsView` with your UI on top of `CameraView` and set `GraphicsView InputTransparent="True"`. See [ScanPage.xaml](https://github.com/afriscic/BarcodeScanning.Native.Maui/blob/master/BarcodeScanning.Test/ScanPage.xaml) for an example. Then in `CameraView_OnDetectionFinished` event you just reject any barcode that is outside your desired region.

**Comment by garcia252** [comment]
Understood, thanks for the reply
