### ISSUE TITLE
Load Image Support

### ISSUE THREAD

**Issue by clEclE36** [afriscic/BarcodeScanning.Native.Maui#66]
Great job on this library !

It works without problems with different versions of Android and iOS, whereas I've had a few problems with other libraries !

Is it possible to load an image that contains a barcode and pass it to an analysis function to detect the barcode ?

ZXing offers this functionality via BarcodeReader classes.

Is it possible to do this with BarcodeScanning as it is, or should we suggest it :D.

Good luck !

**Comment by afriscic** [comment]
Hello.

You can use MAUI built in [File picker](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker) and just pass `FileResult` to `ScanFromImageAsync` method.

**Comment by clEclE36** [comment]
Thank you for your reply !
I'd overlooked it while browsing the code :)
