### ISSUE TITLE
Call to AVCaptureSession.startRunning() blocks

### ISSUE THREAD

**Issue by breyed** [afriscic/BarcodeScanning.Native.Maui#71]
Apple’s documentation for [startRunning()](https://developer.apple.com/documentation/avfoundation/avcapturesession) has this important note:
> The startRunning() method is a blocking call which can take some time, therefore start the session on a serial dispatch queue so that you don’t block the main queue (which keeps the UI responsive). See [AVCam: Building a Camera App](https://developer.apple.com/documentation/avfoundation/capture_setup/avcam_building_a_camera_app) for an implementation example.

This is borne out in practice. On an iPhone 15, the app hangs for about 2 seconds, since BarcodeScanning.Native.Maui calls startRunning() and stopRunning() on the main thread. Sometimes this doesn’t feel too bad, but when navigating to a page that has the barcode scanner already enabled, it feels quite glitchy.

**Comment by afriscic** [comment]
Hello,

thank you for pointing this out. Somehow I missed that. 
I'll fix this in next release.

**Comment by afriscic** [comment]
Should be fixed in 1.5.4
