### ISSUE TITLE
RequestZoomFactor DeadLock after 1.5.4 release on Android

### ISSUE THREAD

**Issue by MartinYanicelli** [afriscic/BarcodeScanning.Native.Maui#75]
After last change for reset RequestZoomFactor value on 1.5.4 release, if you now change the RequestZoomFactor property value we enter a deadlock because the cameramanger UpdateZoomFactor method and the observer onchange method call between them all the time. The workaround for the moment is put additional check on the observer method, something like this:

if (value is not null && _cameraView is not null && value is IZoomState state &&
    _cameraView.CurrentZoomFactor != state.ZoomRatio)

I can't test on iOs because I don't have an iphone but apparently it's not the same case.

Sorry for my english is very poor.

**Comment by MartinYanicelli** [comment]
By the way, thank you so much for the great job!

**Comment by afriscic** [comment]
Totally missed it, thank you! Should be fixed in 1.5.5
