### ISSUE TITLE
Change the barcode format at runtime

### ISSUE THREAD

**Issue by geertgeerits** [afriscic/BarcodeScanning.Native.Maui#9]
Hi,

How can I change the barcode format at runtime?
It tried this: barcodeReader.BarcodeSymbologies.Equals("Ean13");
but this is not working, it still reads all the barcodes.
Thanks in advance.

**Comment by afriscic** [comment]
You can do it like this:
`barcodeReader.BarcodeSymbologies = BarcodeFormats.Ean13;`
Or you can combine multiple symbologies:
`barcodeReader.BarcodeSymbologies = BarcodeFormats.Ean13 | BarcodeFormats.DataMatrix | BarcodeFormats.QRCode;`
