### ISSUE TITLE
Scanning of non Utf-8 QR-Codes on Android

### ISSUE THREAD

**Issue by NcaDev1** [afriscic/BarcodeScanning.Native.Maui#95]
Hello, we noticed that some QR-Codes can't be scanned on Android using the latest version (iOS works fine).

I had a look at the code and found the following issue:

The field RawValue in BarcodeResult is used in GetHashCode. This can lead to a NullReferenceException as the RawValue is null in the MLKit result for non Utf-8 codes (see https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/common/Barcode#public-string-getrawvalue).

Same discussion problem existed also for a react native library, see https://github.com/mrousavy/react-native-vision-camera/issues/2128.

Could you implement a fallback to handle this case?

Thank you!

**Comment by afriscic** [comment]
Hello.
Thank you for the report. I'll fix this in next release

**Comment by NcaDev1** [comment]
Thank you very much for the update, it works as expected.
